baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'About'
pageRef = '/pages/about-me'

[[menus.main]]
name = 'Resources'
pageRef = '/pages/resources'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
