baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'About & Contact'
pageRef = '/pages/about-me'
weight = 25

[[menus.main]]
name = 'Resources'
pageRef = '/pages/resources'
weight = 30

[[menus.main]]
name = 'Knowledge Wiki'
url = 'http://wiki.0xdeadbeer.xyz/'
weight = 33

[[menus.main]]
name = 'Archive'
url = 'http://archive.0xdeadbeer.xyz'
weight = 35

[[menus.main]]
name = 'RSS'
url = '/index.xml'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup.highlight]
    noClasses = false
