baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'about'
pageRef = '/pages/about-me'
weight = 25

[[menus.main]]
name = 'resources'
pageRef = '/pages/resources'
weight = 30

[[menus.main]]
name = 'git'
url = 'http://git.0xdeadbeer.xyz/0xdeadbeer/'
weight = 33

[[menus.main]]
name = 'archive'
url = 'http://archive.0xdeadbeer.xyz'
weight = 35

[[menus.main]]
name = 'rss'
url = '/index.xml'
weight = 40


#[[menus.main]]
#name = 'Tags'
#pageRef = '/tags'
#weight = 35


[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
